import { NextRequest, NextResponse } from "next/server";
import { writeFileSync } from "fs";
import { resolve } from "path";
import { config } from "@/lib/config";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

// GET /api/onboarding/config
// Returns current environment values (for pre-filling the wizard).
export async function GET() {
  return NextResponse.json({
    ok: true,
    githubOrg: config.github.org ?? "",
    splunkHecUrl: config.splunk.hecUrl ?? "",
    splunkHecToken: config.splunk.hecToken ?? "",
    splunkBaseUrl: config.splunk.baseUrl ?? "",
    splunkUsername: config.splunk.username ?? "",
    splunkPassword: config.splunk.password ?? "",
    splunkSkipTlsVerify: config.splunk.skipTlsVerify ? "true" : "",
    deepseekApiKey: config.ai.apiKey ?? "",
    aiProvider: config.ai.provider ?? "deepseek",
  });
}

// POST /api/onboarding/config
// Writes .env.local. Requires app restart for full effect.
export async function POST(req: NextRequest) {
  let body: Record<string, string>;
  try {
    body = await req.json();
  } catch {
    return NextResponse.json({ ok: false, error: "Invalid body" }, { status: 400 });
  }

  const envPath = resolve(process.cwd(), ".env.local");
  const lines = [
    "# ZeroQ — environment configuration",
    "# Generated by onboarding wizard",
    "",
  ];

  const add = (key: string, value?: string) => {
    if (value !== undefined && value !== null) lines.push(`${key}=${value}`);
  };

  add("DEEPSEEK_API_KEY", body.deepseekApiKey);
  add("DEEPSEEK_MODEL", body.deepseekModel || "deepseek-chat");
  add("AI_PROVIDER", body.aiProvider || "deepseek");
  add("GITHUB_ORG", body.githubOrg);
  add("GITHUB_TOKEN", body.githubToken);
  add("GITLAB_TOKEN", body.gitlabToken);
  add("SPLUNK_HEC_URL", body.splunkHecUrl);
  add("SPLUNK_HEC_TOKEN", body.splunkHecToken);
  add("SPLUNK_INDEX_SOURCE", body.splunkIndexSource || "crypto_source");
  add("SPLUNK_BASE_URL", body.splunkBaseUrl);
  add("SPLUNK_USERNAME", body.splunkUsername);
  add("SPLUNK_PASSWORD", body.splunkPassword);
  add("SPLUNK_SKIP_TLS_VERIFY", body.splunkSkipTlsVerify);
  add("SPLUNK_INDEX_NET", body.splunkIndexNet || "crypto_net");
  add("SPLUNK_INDEX_PKI", body.splunkIndexPki || "crypto_pki");
  add("SPLUNK_INDEX_HNDL", body.splunkIndexHndl || "crypto_hndl");
  add("SPLUNK_INDEX_PLAN", body.splunkIndexPlan || "crypto_plan");
  add("SCAN_MAX_FILES", body.scanMaxFiles || "80");

  try {
    writeFileSync(envPath, lines.join("\n") + "\n", "utf8");
    return NextResponse.json({ ok: true, message: "Configuration saved. Please restart the app (npm run dev) for all changes to take effect." });
  } catch (e: any) {
    return NextResponse.json({ ok: false, error: e?.message || "Failed to write config" }, { status: 500 });
  }
}
