import { NextRequest, NextResponse } from "next/server";
import { readFileSync, writeFileSync, mkdirSync, existsSync } from "fs";
import { resolve } from "path";
import { config } from "@/lib/config";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

const DATA_DIR = resolve(process.cwd(), "data");
const SELECTED_REPOS_PATH = resolve(DATA_DIR, "selected-repos.json");

function readSelectedRepos(): string[] {
  try {
    const raw = readFileSync(SELECTED_REPOS_PATH, "utf8");
    const parsed = JSON.parse(raw);
    if (Array.isArray(parsed.selectedRepos)) {
      return parsed.selectedRepos
        .map((s: any) => String(s ?? "").trim())
        .filter((s: string) => s.length > 0);
    }
  } catch {
    // File missing or unreadable — return empty list.
  }
  return [];
}

function writeSelectedRepos(repos: string[]) {
  try {
    mkdirSync(DATA_DIR, { recursive: true });
  } catch { /* ignore */ }
  const normalized = repos
    .map((s) => s.trim())
    .filter((s) => s.length > 0);
  writeFileSync(
    SELECTED_REPOS_PATH,
    JSON.stringify({ selectedRepos: normalized }, null, 2) + "\n",
    "utf8"
  );
}

// GET /api/onboarding/config
// Returns current environment values (for pre-filling the wizard).
export async function GET() {
  return NextResponse.json({
    ok: true,
    githubOrg: config.github.org ?? "",
    selectedRepos: readSelectedRepos(),
    splunkHecUrl: config.splunk.hecUrl ?? "",
    splunkHecToken: config.splunk.hecToken ?? "",
    splunkBaseUrl: config.splunk.baseUrl ?? "",
    splunkUsername: config.splunk.username ?? "",
    splunkPassword: config.splunk.password ?? "",
    splunkSkipTlsVerify: config.splunk.skipTlsVerify ? "true" : "",
    deepseekApiKey: config.ai.apiKey ?? "",
    aiProvider: config.ai.provider ?? "deepseek",
  });
}

// POST /api/onboarding/config
// Writes .env.local, merging with existing values so partial updates
// (e.g. saving only selectedRepos) do not erase other settings.
export async function POST(req: NextRequest) {
  let body: Record<string, any>;
  try {
    body = await req.json();
  } catch {
    return NextResponse.json({ ok: false, error: "Invalid body" }, { status: 400 });
  }

  // Persist selected repositories independently so changes are visible
  // immediately without restarting the dev server.
  if (Array.isArray(body.selectedRepos)) {
    writeSelectedRepos(body.selectedRepos);
  }

  const envPath = resolve(process.cwd(), ".env.local");

  // Read existing env file so we can merge rather than overwrite.
  const existing: Record<string, string> = {};
  try {
    const current = readFileSync(envPath, "utf8");
    for (const line of current.split("\n")) {
      const trimmed = line.trim();
      if (!trimmed || trimmed.startsWith("#")) continue;
      const idx = trimmed.indexOf("=");
      if (idx === -1) continue;
      const key = trimmed.slice(0, idx).trim();
      const value = trimmed.slice(idx + 1).trim();
      existing[key] = value;
    }
  } catch {
    // File may not exist yet; start empty.
  }

  const pick = (key: string, bodyValue?: any, fallback?: string) => {
    if (bodyValue !== undefined) return String(bodyValue ?? "");
    if (existing[key] !== undefined) return existing[key];
    return fallback ?? "";
  };

  const lines = [
    "# ZeroQ — environment configuration",
    "# Generated by onboarding wizard",
    "",
  ];

  const add = (key: string, value: string) => {
    lines.push(`${key}=${value}`);
  };

  add("DEEPSEEK_API_KEY", pick("DEEPSEEK_API_KEY", body.deepseekApiKey, existing["DEEPSEEK_API_KEY"]));
  add("DEEPSEEK_MODEL", pick("DEEPSEEK_MODEL", body.deepseekModel, existing["DEEPSEEK_MODEL"]) || "deepseek-chat");
  add("AI_PROVIDER", pick("AI_PROVIDER", body.aiProvider, existing["AI_PROVIDER"]) || "deepseek");
  add("GITHUB_ORG", pick("GITHUB_ORG", body.githubOrg, existing["GITHUB_ORG"]));
  add("GITHUB_TOKEN", pick("GITHUB_TOKEN", body.githubToken, existing["GITHUB_TOKEN"]));
  add("GITLAB_TOKEN", pick("GITLAB_TOKEN", body.gitlabToken, existing["GITLAB_TOKEN"]));
  add("SPLUNK_HEC_URL", pick("SPLUNK_HEC_URL", body.splunkHecUrl, existing["SPLUNK_HEC_URL"]));
  add("SPLUNK_HEC_TOKEN", pick("SPLUNK_HEC_TOKEN", body.splunkHecToken, existing["SPLUNK_HEC_TOKEN"]));
  add("SPLUNK_INDEX_SOURCE", pick("SPLUNK_INDEX_SOURCE", body.splunkIndexSource, existing["SPLUNK_INDEX_SOURCE"]) || "crypto_source");
  add("SPLUNK_BASE_URL", pick("SPLUNK_BASE_URL", body.splunkBaseUrl, existing["SPLUNK_BASE_URL"]));
  add("SPLUNK_USERNAME", pick("SPLUNK_USERNAME", body.splunkUsername, existing["SPLUNK_USERNAME"]));
  add("SPLUNK_PASSWORD", pick("SPLUNK_PASSWORD", body.splunkPassword, existing["SPLUNK_PASSWORD"]));
  add("SPLUNK_SKIP_TLS_VERIFY", pick("SPLUNK_SKIP_TLS_VERIFY", body.splunkSkipTlsVerify, existing["SPLUNK_SKIP_TLS_VERIFY"]));
  add("SPLUNK_INDEX_NET", pick("SPLUNK_INDEX_NET", body.splunkIndexNet, existing["SPLUNK_INDEX_NET"]) || "crypto_net");
  add("SPLUNK_INDEX_PKI", pick("SPLUNK_INDEX_PKI", body.splunkIndexPki, existing["SPLUNK_INDEX_PKI"]) || "crypto_pki");
  add("SPLUNK_INDEX_HNDL", pick("SPLUNK_INDEX_HNDL", body.splunkIndexHndl, existing["SPLUNK_INDEX_HNDL"]) || "crypto_hndl");
  add("SPLUNK_INDEX_PLAN", pick("SPLUNK_INDEX_PLAN", body.splunkIndexPlan, existing["SPLUNK_INDEX_PLAN"]) || "crypto_plan");
  add("SCAN_MAX_FILES", pick("SCAN_MAX_FILES", body.scanMaxFiles, existing["SCAN_MAX_FILES"]) || "80");

  try {
    writeFileSync(envPath, lines.join("\n") + "\n", "utf8");
    return NextResponse.json({ ok: true, message: "Configuration saved. Please restart the app (npm run dev) for env changes to take effect. Selected repositories are active immediately." });
  } catch (e: any) {
    return NextResponse.json({ ok: false, error: e?.message || "Failed to write config" }, { status: 500 });
  }
}
