[crypto_source]
homePath = $SPLUNK_DB/crypto_source/db
coldPath = $SPLUNK_DB/crypto_source/colddb
thawedPath = $SPLUNK_DB/crypto_source/thaweddb

[crypto_net]
homePath = $SPLUNK_DB/crypto_net/db
coldPath = $SPLUNK_DB/crypto_net/colddb
thawedPath = $SPLUNK_DB/crypto_net/thaweddb

[crypto_pki]
homePath = $SPLUNK_DB/crypto_pki/db
coldPath = $SPLUNK_DB/crypto_pki/colddb
thawedPath = $SPLUNK_DB/crypto_pki/thaweddb

[crypto_hndl]
homePath = $SPLUNK_DB/crypto_hndl/db
coldPath = $SPLUNK_DB/crypto_hndl/colddb
thawedPath = $SPLUNK_DB/crypto_hndl/thaweddb

[crypto_plan]
homePath = $SPLUNK_DB/crypto_plan/db
coldPath = $SPLUNK_DB/crypto_plan/colddb
thawedPath = $SPLUNK_DB/crypto_plan/thaweddb
